#  -- 创建时设置兼容模式，openGauss可通过该命令创建兼容MySQL语法的数据库
#    CREATE DATABASE metal_micro_wire DBCOMPATIBILITY = 'B';

spring:
  application:
    name: metal_micro_wire_backend

  # 数据库配置
  # datasource:
  #   url: jdbc:mysql://localhost:3306/metal_micro_wire?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
  #   username: username
  #   password: password
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres?useSSL=false&serverTimezone=Asia/Shanghai
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    # 是否显示SQL语句
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  # 邮件配置
  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true

  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      # password: 如有密码请取消注释
      database: 2
      timeout: 10000

# JWT Token配置
jwt:
  # 请修改为随机字符串(jwt密钥)
  secret: metal_micro_wire_secret_key_2024_very_secure_random_key_for_jwt_signing
  # 普通登录过期时间（小时）
  expiration-normal: 2
  # 记住登录过期时间（小时）
  expiration-remember: 168

# 验证码配置
verification:
  # 验证码有效期（分钟）
  code-expire-minutes: 5
  # 验证码发送冷却时间（秒）
  send-cooldown-seconds: 60

# 华为云IoT配置
huawei:
  iot:
    # SDK配置 - 用于主动推送消息到设备
    ak: HPUARWPPVCIQHLXUGBSA
    sk: ae8wCDrJQkLUNaqSYwYEXA71tYMXSeYfo1dImQXf
    endpoint: https://1ef972c084.st1.iotda-app.cn-north-4.myhuaweicloud.com
    project-id: 768eb2550b2146a39048ba0330c487c9
    region: cn-north-4

    # AMQP连接配置 - 用于接收设备消息
    amqp:
      host: 1ef972c084.st1.iotda-app.cn-north-4.myhuaweicloud.com
      port: 5671
      access-key: JOPvCH6V
      access-code: Y94aIdqb3BND7fFm6RqZTDieXn7I2bWE
      default-queue: DefaultQueue
      # 连接配置
      queue-prefetch: 100
      auto-acknowledge: true
      reconnect-delay: 3000
      max-reconnect-delay: 30000
    # 消息处理配置
    message:
      # 是否启用详细日志
      enable-detailed-logging: true
      # 最大消息大小（字符数）
      max-message-size: 1000000

# 示例配置
example:
  # 华为云IoT消息推送示例
  huawei-iot:
    # 是否启用华为云IoT消息推送示例（启动时自动运行）
    enabled: false

# 机器学习模型配置
ml:
  model:
    api:
      # 机器学习模型API服务地址
      url: http://localhost:5000
      # 请求超时时间（毫秒）
      timeout: 30000
    # 置信度阈值配置
    confidence:
      # 置信度阈值，低于此值需要人工审核
      threshold: 0.8
    # 是否启用机器学习模型评估
    enabled: true
    # 健康检查配置
    health-check:
      # 健康检查间隔（分钟）
      interval: 5
      # 健康检查超时时间（毫秒）
      timeout: 5000

# 质量溯源系统配置
app:
  # 通知配置
  notification:
    # 是否启用邮件通知
    email-enabled: true

    # 质量问题判定阈值配置（百分比）
    fail-rate-threshold: 5.0              # 基础不合格率阈值
    critical-fail-rate-threshold: 10.0    # 严重问题阈值
    high-risk-fail-rate-threshold: 8.0    # 高风险问题阈值
    medium-risk-fail-rate-threshold: 6.0  # 中等风险问题阈值

    # 管理员邮箱列表（接收汇总报告和严重问题通知）
    admin-emails:
      - 3106133216@qq.com
      - 3115089759@qq.com

    # 邮件发送配置
    email-retry-count: 3        # 邮件发送重试次数
    email-retry-interval: 5000  # 邮件发送重试间隔（毫秒）

  # 质量监控定时任务配置
  quality-monitor:
    # 是否启用质量监控定时任务
    enabled: true
    # 定时任务执行频率（cron表达式）
    # 格式：秒 分 时 日 月 周
    # 示例：
    # "0 0 0 * * ?"     - 每天凌晨执行一次（推荐）
    # "0 0 * * * ?"     - 每小时执行一次
    # "0 */30 * * * ?"  - 每30分钟执行一次
    # "0 0 */2 * * ?"   - 每2小时执行一次
    cron: "0 0 0 * * ?"
    # 检测时间窗口（小时）- 检测前N小时的数据
    detection-window-hours: 24
    # 是否向管理员发送无问题确认邮件
    send-no-issue-notification-to-admin: true
    # 质量问题判定阈值（百分比）
    fail-rate-threshold: 5.0

  # 质量报告生成配置
  quality-report:
    # 是否启用质量报告生成
    enabled: true
    # 报告生成频率（cron表达式）
    # 示例：
    # "0 0 2 * * ?"     - 每天凌晨2点执行
    # "0 0 8 * * MON"   - 每周一上午8点执行
    # "0 0 9 1 * ?"     - 每月1号上午9点执行
    cron: "0 0 2 * * ?"

server:
  port: 8080
