#  -- 创建时设置兼容模式，openGauss可通过该命令创建兼容MySQL语法的数据库
#    CREATE DATABASE metal_micro_wire DBCOMPATIBILITY = 'B';

spring:
  application:
    name: metal_micro_wire_backend

  # Spring Boot文件上传配置
  servlet:
    multipart:
      # 最大文件大小
      max-file-size: 2MB
      # 最大请求大小
      max-request-size: 2MB

  # 数据库配置
  # datasource:
  #   url: jdbc:mysql://localhost:3306/metal_micro_wire?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
  #   username: username
  #   password: password
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres?useSSL=false&serverTimezone=Asia/Shanghai
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    # 是否显示SQL语句
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  # 邮件配置
  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true

  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      # password: 如有密码请取消注释
      database: 2
      timeout: 10000

# JWT Token配置
jwt:
  # 请修改为随机字符串(jwt密钥)
  secret: metal_micro_wire_secret_key_2024_very_secure_random_key_for_jwt_signing
  # 普通登录过期时间（小时）
  expiration-normal: 2
  # 记住登录过期时间（小时）
  expiration-remember: 168

# 验证码配置
verification:
  # 验证码有效期（分钟）
  code-expire-minutes: 5
  # 验证码发送冷却时间（秒）
  send-cooldown-seconds: 60

# 华为云IoT配置
huawei:
  iot:
    # SDK配置 - 用于主动推送消息到设备
    ak: HPUARWPPVCIQHLXUGBSA
    sk: ae8wCDrJQkLUNaqSYwYEXA71tYMXSeYfo1dImQXf
    endpoint: https://1ef972c084.st1.iotda-app.cn-north-4.myhuaweicloud.com
    project-id: 768eb2550b2146a39048ba0330c487c9
    region: cn-north-4

    # AMQP连接配置 - 用于接收设备消息
    amqp:
      host: 1ef972c084.st1.iotda-app.cn-north-4.myhuaweicloud.com
      port: 5671
      access-key: JOPvCH6V
      access-code: Y94aIdqb3BND7fFm6RqZTDieXn7I2bWE
      default-queue: DefaultQueue
      # 连接配置
      queue-prefetch: 100
      auto-acknowledge: true
      reconnect-delay: 3000
      max-reconnect-delay: 30000
    # 消息处理配置
    message:
      # 是否启用详细日志
      enable-detailed-logging: true
      # 最大消息大小（字符数）
      max-message-size: 1000000

# 示例配置
example:
  # 华为云IoT消息推送示例
  huawei-iot:
    # 是否启用华为云IoT消息推送示例（启动时自动运行）
    enabled: false

# 机器学习模型配置
ml:
  model:
    api:
      # 机器学习模型API服务地址
      url: http://localhost:5000
      # 请求超时时间（毫秒）
      timeout: 30000
    # 置信度阈值配置
    confidence:
      # 置信度阈值，低于此值需要人工审核
      threshold: 0.8
    # 是否启用机器学习模型评估
    enabled: true
    # 健康检查配置
    health-check:
      # 健康检查间隔（分钟）
      interval: 5
      # 健康检查超时时间（毫秒）
      timeout: 5000

app:
  # 文件上传配置
  file-upload:
    # 文件上传根目录
    upload-path: uploads
    # 头像上传子目录
    avatar-path: avatars
    # 最大文件大小（字节）- 2MB
    max-file-size: 2097152
    # 文件访问URL前缀
    url-prefix: /api/files
  # 通知配置
  notification:
    # 是否启用邮件通知
    email-enabled: true

    # 质量问题判定阈值配置（百分比）
    fail-rate-threshold: 5.0              # 基础不合格率阈值
    critical-fail-rate-threshold: 10.0    # 严重问题阈值
    high-risk-fail-rate-threshold: 8.0    # 高风险问题阈值
    medium-risk-fail-rate-threshold: 6.0  # 中等风险问题阈值

    # 管理员邮箱列表（接收汇总报告和严重问题通知）
    admin-emails:
      - 3106133216@qq.com
      - 3115089759@qq.com

    # 邮件发送配置
    email-retry-count: 3        # 邮件发送重试次数
    email-retry-interval: 5000  # 邮件发送重试间隔（毫秒）

  # 质量监控定时任务配置
  quality-monitor:
    # 是否启用质量监控定时任务
    enabled: true
    # 定时任务执行频率（cron表达式）
    # 格式：秒 分 时 日 月 周
    # 示例：
    # "0 0 0 * * ?"     - 每天凌晨执行一次（推荐）
    # "0 0 * * * ?"     - 每小时执行一次
    # "0 */30 * * * ?"  - 每30分钟执行一次
    # "0 0 */2 * * ?"   - 每2小时执行一次
    cron: "0 0 0 * * ?"
    # 检测时间窗口（小时）- 检测前N小时的数据
    detection-window-hours: 24
    # 是否向管理员发送无问题确认邮件
    send-no-issue-notification-to-admin: true
    # 质量问题判定阈值（百分比）
    fail-rate-threshold: 5.0

  # 质量报告生成配置
  quality-report:
    # 是否启用质量报告生成
    enabled: true
    # 报告生成频率（cron表达式）
    # 示例：
    # "0 0 2 * * ?"     - 每天凌晨2点执行
    # "0 0 8 * * MON"   - 每周一上午8点执行
    # "0 0 9 1 * ?"     - 每月1号上午9点执行
    cron: "0 0 2 * * ?"

server:
  port: 8080

# DeepSeek大语言模型配置
deepseek:
  # API配置
  api:
    # API基础URL
    base-url: https://api.deepseek.com
    # API密钥 - 请替换为您的实际API密钥
    api-key: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    # 连接超时时间（秒）
    connect-timeout: 30
    # 读取超时时间（秒）
    read-timeout: 60
    # 是否启用DeepSeek服务
    enabled: true
  
  # 模型配置
  model:
    # 默认模型名称
    default-model: deepseek-chat
    # 最大tokens数
    max-tokens: 4096
    # 温度参数（0.0-1.0）
    temperature: 0.7
    # 系统提示词
    system-prompt: |
      你是金属微细线材综合检测平台的智能助手，专门为用户提供线材检测、质量分析和设备管理相关的服务。

      ## 可用工具函数（共11个）

      ### 1. 设备管理工具（2个）
      - **get_device_list**: 获取设备列表，支持分页和状态筛选（ON/OFF）
      - **get_device_info**: 根据设备ID获取设备详细信息

      ### 2. 线材检测数据工具（2个）
      - **get_wire_material_list**: 获取金属微丝检测数据列表，支持批次号、生产商、场景筛选
      - **get_wire_material_info**: 根据批次号获取线材详细检测信息和质量参数

      ### 3. 质量分析工具（3个）
      - **analyze_quality_issues**: 执行质量问题溯源分析，支持按生产商、负责人、工艺类型、生产机器、应用场景等维度分析
      - **get_quality_issues**: 获取质量问题列表，识别不合格的线材批次
      - **get_manufacturer_ranking**: 获取生产商质量排名，分析各生产商的质量表现

      ### 4. 统计分析工具（3个）
      - **get_overall_statistics**: 获取系统总体统计数据（总检测数量、合格率、设备数量等）
      - **get_yearly_statistics**: 获取最近12个月的年度检测数据统计
      - **get_scenario_statistics**: 根据时间范围获取应用场景统计数据

      ### 5. 系统工具（1个）
      - **get_current_time**: 获取当前系统时间和日期信息，支持多种格式（datetime/date/time/timestamp）

      ## 工具调用策略
      如果想要调用工具，请使用OpenAI格式的工具调用

      ### 多步骤分析流程
      当用户请求复杂分析时，按以下顺序组合工具：
      1. **时间确定**：如涉及"今天"、"本月"等时间概念，先调用get_current_time获取准确时间
      2. **数据收集**：根据需求调用相应的数据获取工具（设备、线材、质量等）
      3. **深度分析**：使用分析工具进行质量溯源、排名对比等
      4. **统计汇总**：调用统计工具提供整体数据概览

      ### 常见任务的工具组合
      - **今日检测数据分析**：get_current_time → get_device_list → get_wire_material_list → get_overall_statistics
      - **质量问题调查**：get_quality_issues → analyze_quality_issues → get_manufacturer_ranking
      - **生产商评估**：get_manufacturer_ranking → analyze_quality_issues → get_wire_material_list
      - **设备状态检查**：get_device_list → get_device_info → get_overall_statistics
      - **时间范围分析**：get_current_time → get_scenario_statistics → get_yearly_statistics

      ## 重要约束
      - **严禁调用不存在的工具**：只能使用上述11个明确定义的工具函数
      - **参数准确性**：确保传递给工具的参数格式正确，特别是时间格式（yyyy-MM-dd HH:mm:ss）
      - **逐步执行**：复杂任务需要分步骤执行，不要尝试一次性获取所有数据
      - **错误处理**：如果工具调用失败，提供替代方案或建议用户检查参数

      ## 工作原则
      - **数据驱动**：所有分析必须基于工具获取的实时数据
      - **专业准确**：使用准确的技术术语，提供专业的分析建议
      - **用户友好**：将复杂的技术信息转化为易懂的表述
      - **主动建议**：根据数据结果主动提供相关的查询或分析建议

      ## 响应模式
      1. **理解需求**：准确理解用户的查询意图
      2. **规划步骤**：确定需要调用的工具和执行顺序
      3. **执行调用**：按计划逐步调用工具获取数据
      4. **分析整合**：整合多个工具的结果进行综合分析
      5. **提供建议**：基于数据分析提供专业建议和后续行动建议

      请用中文回答用户的问题，严格按照上述工具列表和调用策略执行任务。
  
  # 会话配置
  session:
    # 会话过期时间（小时）
    expire-hours: 24
    # 每个用户最大会话数
    max-sessions-per-user: 10
    # 每个会话最大消息数
    max-messages-per-session: 100
    # 会话标题最大长度
    max-title-length: 50
